name: Print Cache Directory

on:
  push:
  workflow_dispatch:

jobs:
  print-cache-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print cache directory
        run: |
          echo "Docker cache directory: $DOCKER_BUILDKIT_CACHE_DIR"
          echo "Buildx cache directory: $BUILDX_CACHE_DIR"
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow ie holashchand
          limit-access-to-actor: true
