name: Print Cache Directory

on:
  push:
  workflow_dispatch:

jobs:
  print-cache-directory:
    runs-on: ubuntu-latest
    env:
      BUILD_VERSION: $(git rev-parse --short HEAD)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        id: maven-cache
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('java/pom.xml','**/pom.xml', 'services/*/pom.xml', 'java/*/pom.xml', 'java/*/*/pom.xml', 'java/*/*/*/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Print cache directory
        run: |
          echo "Docker cache directory: $DOCKER_BUILDKIT_CACHE_DIR"
          echo "Buildx cache directory: $BUILDX_CACHE_DIR"
          echo "Buildx cache directory: $BUILD_VERSION"
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      #   with:
      #     ## limits ssh access and adds the ssh public key for the user which triggered the workflow ie holashchand
      #     limit-access-to-actor: true
