name: Print Cache Directory

on:
  push:
  workflow_dispatch:

jobs:
  print-cache-directory:
    runs-on: macos-13
    env:
      BUILD_VERSION: $(git rev-parse --short HEAD)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow ie holashchand
          limit-access-to-actor: true
