name: Print Cache Directory

on:
  push:
  workflow_dispatch:

jobs:
  print-cache-directory:
    runs-on: macos-13
    env:
      BUILD_VERSION: $(git rev-parse --short HEAD)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Tmate
        run: |
            brew install tmate

      - name: Configure SSH Access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.USER_SSH_KEY }}" >> ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          chmod 700 ~/.ssh

      - name: Start Tmate Session
        run: |
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}' > tmatesh
          tmate -S /tmp/tmate.sock display -p '#{tmate_web}' > tmateweb
          echo "SSH access: $(cat tmatesh)"
          echo "Web access: $(cat tmateweb)"
          sleep 1h  # Keeps the session open for 1 hour

      - name: Stop Tmate Session
        if: always()
        run: |
          tmate -S /tmp/tmate.sock kill-server
#      - name: Setup upterm session
#        uses: lhotari/action-upterm@v1
#        with:
#          ## limits ssh access and adds the ssh public key for the user which triggered the workflow ie holashchand
#          limit-access-to-actor: true
